repos:
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
  - id: markdownlint
    name: markdownlint
    description: "Checks the style of Markdown/Commonmark files."
    entry: markdownlint
    language: node
    types: [markdown]
    minimum_pre_commit_version: 0.15.0
